### ISSUE TITLE
F1 scores

### ISSUE THREAD

**Issue by natny** [YerevaNN/mimic3-benchmarks#18]
Hello again, 

I have noticed that in the file metrics.py, there's code to compute precision and recall. However, you seem to be converting inputs to binary arrays:
metrics.precision_score(y_true > 0.5, predictions > 0.5, average="micro")
If I need to compute the F1 scores, is this the way to go? Why can't I use the raw values of y and y^?

Thanks!

**Comment by Harhro94** [comment]
Hi @natny,

In this case `y_true` is a binary array with shape `(S, 25)`. `predictions` is an array with the same shape. Each value in `predictions` is between 0 and 1. To calculate precision and recall we must select a threshold to convert our predictions (which are some kind of confidences) into binary labels. As you see, I use 0.5 as the threshold. Also, as we have more than one classification task, then we need to average in some way. We use micro averaging. After you have the precision and recall you can calculate the F1 score.

On note: We don't care about precision and recall, as for them you select a threshold and they are very sensitive to class imbalance. That's why we use AUC of ROC as the main metric.

**Comment by natny** [comment]
Hi Harhro, I have been reading up on them and thanks for taking the time to clarify. I did realise that auroc are computed at different thresholds and F1 is not. Thank you.
