### ISSUE TITLE
Minor issue in preprocessing demographics

### ISSUE THREAD

**Issue by Taha-Bahadori** [YerevaNN/mimic3-benchmarks#27]
I believe the following is a better ways of processing the demographics:
```python
e_map = {'ASIAN': 1,
         'BLACK': 2,
         'CARIBBEAN ISLAND': 2,
         'HISPANIC': 3,
         'SOUTH AMERICAN': 3,
         'WHITE': 4,
         'MIDDLE EASTERN': 4,
         'PORTUGUESE': 4,
         'AMERICAN INDIAN': 5,
         'NATIVE HAWAIIAN': 6,
         'UNABLE TO OBTAIN': 0,
         'PATIENT DECLINED TO ANSWER': 0,
         'UNKNOWN': 0,
         '': 0}
```
Your preprocessing ignores _American Indians_ and _Native Hawaiians_ and also does not treat _Caribbean Islanders_, _South Americans_, _Middle Easterns_ properly.

**Comment by turambar** [comment]
@Taha-Bahadori good catch.

So if I understand correctly, you are proposing the following changes

- eliminate old group 5 for "OTHER"
- add new groups 5 and 6 for AMERICAN INDIAN and NATIVE HAWAIIAN
- map AMERICAN INDIAN to new group 5 instead of 0
- map CARIBBEAN ISLAND to 2 (with BLACK) instead of "OTHER"
- map SOUTH AMERICAN to 3 (with HISPANIC) instead of "OTHER"
- map MIDDLE EASTERN to 4 (with WHITE) instead of "OTHER"
- map PORTUGESE to 4 (with WHITE) instead of "OTHER"

That all makes sense to me -- my primary concern regards the sizes of groups 5 (AMERICAN INDIAN: 54) and 6 (NATIVE HAWAIIAN: 18). Those are pretty small, and they might get smaller after filtering.

Regardless I think we'll add some version of your proposal to the next release, which is coming soon.

**Comment by turambar** [comment]
PR: https://github.com/YerevaNN/mimic3-benchmarks/pull/33

**Comment by Taha-Bahadori** [comment]
Based on your statistics, I think we can easily merge `AMERICAN INDIAN` and `NATIVE HAWAIIAN` categories to 0 category (which is essentially everything else). I also understand that `UNKOWN`, `DECLINED`, and `UNABLE` are conceptually different from those two but I think statistically this won't make any difference.

**Comment by turambar** [comment]
See this PR: https://github.com/YerevaNN/mimic3-benchmarks/pull/33

Will merge the PR soon now that the 1.0 release is done.

**Comment by Harhro94** [comment]
Merged !
