### ISSUE TITLE
In-Hospital Mortality -- Number of patients in datasets

### ISSUE THREAD

**Issue by mmayo888** [YerevaNN/mimic3-benchmarks#50]
Hi, I've run your scripts to generate the datasets for the in-hospital-mortality task but I've found that there are substantially fewer patients in the train/val/test listfiles than is reported in the paper. In the paper (Section 2.1 at the end) it's reported that there are 42,276 patients in the dataset. However the numbers of patients I get are:

  3236 test_listfile.csv
 14681 train_listfile.csv
  3222 val_listfile.csv
 21139 total 

Is there an error in the paper or have I done something wrong?

**Comment by Harhro94** [comment]
Hi @mmayo888, after processing the MIMIC-III dataset we get 42,276 patients. Not all of the patients are present in present in in-hospital-mortality task, since some of them have shorter than 48 hour stays. 
The last sentence of Section 2.1 just shows the ratio of died patients (not the best way to do that).
 
FYI, we are updating the paper. The new version will have much more details and experiments.

**Comment by mmayo888** [comment]
ok thanks
